import * as fs from "fs";
import * as path from "path";
import { normalizeToKey } from "../src/lib/normalize";

interface CountryData {
  name: string;
  population: number;
  percentageInRegion: number;
  percentageInAfrica: number;
  ethnicityCount: number;
}

interface EthnicityInRegion {
  name: string;
  totalPopulationInRegion: number;
  percentageInRegion: number;
  percentageInAfrica: number;
}

interface DatasetIndex {
  totalPopulationAfrica: number;
  regions: Record<
    string,
    {
      name: string;
      totalPopulation: number;
      countries: Record<string, CountryData>;
      ethnicities: Record<string, EthnicityInRegion>;
    }
  >;
}

// Mapping des noms de régions vers leurs traductions
// Les régions utilisent déjà des clés (afrique_australe, etc.)
const REGION_TRANSLATIONS: Record<
  string,
  { en: string; es: string; pt: string }
> = {
  afrique_du_nord: {
    en: "North Africa",
    es: "África del Norte",
    pt: "África do Norte",
  },
  afrique_de_l_ouest: {
    en: "West Africa",
    es: "África Occidental",
    pt: "África Ocidental",
  },
  afrique_centrale: {
    en: "Central Africa",
    es: "África Central",
    pt: "África Central",
  },
  afrique_de_l_est: {
    en: "East Africa",
    es: "África Oriental",
    pt: "África Oriental",
  },
  afrique_australe: {
    en: "Southern Africa",
    es: "África Austral",
    pt: "África Austral",
  },
};

function main() {
  const indexPath = path.join(process.cwd(), "dataset", "result", "index.json");
  const indexContent = fs.readFileSync(indexPath, "utf-8");
  const index: DatasetIndex = JSON.parse(indexContent);

  // Collecter toutes les entités
  const regions: Record<
    string,
    { en: string; fr: string; es: string; pt: string }
  > = {};
  const countries: Record<
    string,
    { en: string; fr: string; es: string; pt: string }
  > = {};
  const ethnicities: Record<
    string,
    { en: string; fr: string; es: string; pt: string }
  > = {};

  // Traiter les régions
  for (const [regionKey, regionData] of Object.entries(index.regions)) {
    const frName = regionData.name;
    const translations = REGION_TRANSLATIONS[regionKey] || {
      en: frName,
      es: frName,
      pt: frName,
    };
    regions[regionKey] = {
      en: translations.en,
      fr: frName,
      es: translations.es,
      pt: translations.pt,
    };
  }

  // Traiter les pays
  const countrySet = new Set<string>();
  for (const regionData of Object.values(index.regions)) {
    for (const countryName of Object.keys(regionData.countries)) {
      countrySet.add(countryName);
    }
  }

  for (const countryName of Array.from(countrySet).sort()) {
    const key = normalizeToKey(countryName);
    // Pour l'instant, utiliser le nom français comme valeur par défaut
    // Les traductions devront être ajoutées manuellement
    countries[key] = {
      en: countryName, // TODO: traduire
      fr: countryName,
      es: countryName, // TODO: traduire
      pt: countryName, // TODO: traduire
    };
  }

  // Traiter les ethnies
  const ethnicitySet = new Set<string>();
  for (const regionData of Object.values(index.regions)) {
    for (const ethnicityName of Object.keys(regionData.ethnicities)) {
      ethnicitySet.add(ethnicityName);
    }
  }

  for (const ethnicityName of Array.from(ethnicitySet).sort()) {
    const key = normalizeToKey(ethnicityName);
    // Pour l'instant, utiliser le nom français comme valeur par défaut
    // Les traductions devront être ajoutées manuellement
    ethnicities[key] = {
      en: ethnicityName, // TODO: traduire
      fr: ethnicityName,
      es: ethnicityName, // TODO: traduire
      pt: ethnicityName, // TODO: traduire
    };
  }

  // Générer les mappings nom ↔ clé
  const regionNameToKey: Record<string, string> = {};
  const regionKeyToName: Record<string, string> = {};
  const countryNameToKey: Record<string, string> = {};
  const countryKeyToName: Record<string, string> = {};
  const ethnicityNameToKey: Record<string, string> = {};
  const ethnicityKeyToName: Record<string, string> = {};

  // Mapper les régions
  for (const [regionKey, regionData] of Object.entries(index.regions)) {
    const name = regionData.name;
    regionNameToKey[name] = regionKey;
    regionKeyToName[regionKey] = name;
  }

  // Mapper les pays
  for (const countryName of Array.from(countrySet).sort()) {
    const key = normalizeToKey(countryName);
    countryNameToKey[countryName] = key;
    countryKeyToName[key] = countryName;
  }

  // Mapper les ethnies
  for (const ethnicityName of Array.from(ethnicitySet).sort()) {
    const key = normalizeToKey(ethnicityName);
    ethnicityNameToKey[ethnicityName] = key;
    ethnicityKeyToName[key] = ethnicityName;
  }

  // Générer le fichier entityTranslations.ts
  const translationsOutput = `// This file is auto-generated by scripts/generateTranslations.ts
// DO NOT EDIT MANUALLY - Run the script to regenerate

export const entityTranslations = {
  regions: ${JSON.stringify(regions, null, 2)},
  countries: ${JSON.stringify(countries, null, 2)},
  ethnicities: ${JSON.stringify(ethnicities, null, 2)},
} as const;
`;

  const translationsPath = path.join(
    process.cwd(),
    "src",
    "lib",
    "entityTranslations.ts"
  );
  fs.writeFileSync(translationsPath, translationsOutput, "utf-8");

  // Générer le fichier entityKeys.ts avec mappings statiques
  const keysOutput = `// This file is auto-generated by scripts/generateTranslations.ts
// DO NOT EDIT MANUALLY - Run the script to regenerate

// Mappings statiques nom ↔ clé
const regionNameToKey: Record<string, string> = ${JSON.stringify(regionNameToKey, null, 2)};
const regionKeyToName: Record<string, string> = ${JSON.stringify(regionKeyToName, null, 2)};
const countryNameToKey: Record<string, string> = ${JSON.stringify(countryNameToKey, null, 2)};
const countryKeyToName: Record<string, string> = ${JSON.stringify(countryKeyToName, null, 2)};
const ethnicityNameToKey: Record<string, string> = ${JSON.stringify(ethnicityNameToKey, null, 2)};
const ethnicityKeyToName: Record<string, string> = ${JSON.stringify(ethnicityKeyToName, null, 2)};

// Fonctions pour convertir nom → clé
export function getRegionKey(regionName: string): string | null {
  return regionNameToKey[regionName] || null;
}

export function getCountryKey(countryName: string): string | null {
  return countryNameToKey[countryName] || null;
}

export function getEthnicityKey(ethnicityName: string): string | null {
  return ethnicityNameToKey[ethnicityName] || null;
}

// Fonctions pour convertir clé → nom
export function getRegionName(regionKey: string): string | null {
  return regionKeyToName[regionKey] || null;
}

export function getCountryName(countryKey: string): string | null {
  return countryKeyToName[countryKey] || null;
}

export function getEthnicityName(ethnicityKey: string): string | null {
  return ethnicityKeyToName[ethnicityKey] || null;
}

// Fonctions pour obtenir toutes les clés
export function getAllRegionKeys(): string[] {
  return Object.keys(regionKeyToName);
}

export function getAllCountryKeys(): string[] {
  return Object.keys(countryKeyToName);
}

export function getAllEthnicityKeys(): string[] {
  return Object.keys(ethnicityKeyToName);
}
`;

  const keysPath = path.join(process.cwd(), "src", "lib", "entityKeys.ts");
  fs.writeFileSync(keysPath, keysOutput, "utf-8");

  console.log(`✅ Generated translations file: ${translationsPath}`);
  console.log(`✅ Generated entity keys file: ${keysPath}`);
  console.log(`   - ${Object.keys(regions).length} regions`);
  console.log(`   - ${Object.keys(countries).length} countries`);
  console.log(`   - ${Object.keys(ethnicities).length} ethnicities`);
  console.log(
    `\n⚠️  Note: Many translations are placeholders (using French names).`
  );
  console.log(
    `   Please update the translations manually in entityTranslations.ts`
  );
}

main();
